// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chain-dci/pkg/app"
	"chain-dci/pkg/bccr"
	"chain-dci/pkg/logger"
	"chain-dci/pkg/snowf"
	"chain-dci/pkg/tracing"
)

import (
	_ "chain-dci/internal/handler"
	_ "dubbo.apache.org/dubbo-go/v3/filter/tps/strategy"
	_ "dubbo.apache.org/dubbo-go/v3/imports"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	zapLogger := logger.ZapInit()
	jaegerProvider := tracing.NewTracing()
	client := bccr.NewBccrClient()
	node := snowf.NewSf()
	appApp := NewApp(zapLogger, jaegerProvider, client, node)
	return appApp, nil
}
